// lib/constants/fieldIds.ts
export const PROJECT_FIELDS = {
  RECORD_ID: 6,
  CUSTOMER_NAME: 7,
  PROJECT_STATUS: 8,
  ON_HOLD: 9,
  HOLD_REASON: 10,
  DATE_ON_HOLD: 11,
  SYSTEM_PRICE: 12,
  SALES_DATE: 13,
  CLOSER_ID: 516,
  SETTER_ID: 329,
  GROSS_PPW: 19,
  NET_PPW: 543,
  COMMISSIONABLE_PPW: 2480,
  INSTALL_DATE_PRIMARY: 710,
  INSTALL_DATE_BACKUP: 534,
  SURVEY_DATE_PRIMARY: 164,
  SURVEY_DATE_BACKUP: 575,
  DESIGN_DATE_PRIMARY: 315,
  DESIGN_DATE_BACKUP: 476,
  PERMIT_DATE_PRIMARY: 207,
  PERMIT_DATE_BACKUP: 709,
  NEM_DATE_PRIMARY: 326,
  NEM_DATE_BACKUP: 716,
  HOA_DATE_PRIMARY: 212,
  HOA_DATE_BACKUP: 213,
  INSPECTION_DATE: 491,
  PTO_DATE_PRIMARY: 537,
  PTO_DATE_BACKUP: 538,
  STATUS_BAR: 301,
  // Task count fields (enriched from Task Groups table, not native QB fields)
  TOTAL_TASKS: 9999,
  UNAPPROVED_TASKS: 9998
} as const;

// Task-related field constants
export const TASK_GROUP_FIELDS = {
  RECORD_ID: 3,
  RELATED_PROJECT: 10,
  TOTAL_TASKS: 31,
  UNAPPROVED_TASKS: 32
} as const;

export const TASK_FIELDS = {
  RECORD_ID: 3,
  TASK_GROUP: 6,
  STATUS: 9,
  NAME: 10,
  CATEGORY: 31,
  MAX_SUBMISSION_STATUS: 13
} as const;

export const TASK_SUBMISSION_FIELDS = {
  RECORD_ID: 3,
  DATE_CREATED: 1,
  RELATED_TASK: 6,
  SUBMISSION_STATUS: 7,
  OPS_DISPOSITION: 8,
  FILE_ATTACHMENTS: 9
} as const;

// QuickBase table IDs
export const QB_TABLE_TASK_GROUPS = 'bu36gem4p';
export const QB_TABLE_TASKS = 'bu36ggiht';
export const QB_TABLE_TASK_SUBMISSIONS = 'bu36g8j99';