// lib/constants/offices.ts

export const CANONICAL_OFFICES = [
  'Phoenix',
  'Austin', 
  'Dallas',
  'Houston',
  'Tucson',
  'Las Vegas',
  'Denver',
  'Salt Lake City',
  'Albuquerque',
  'San Antonio',
  'El Paso',
  'Oklahoma City',
  'Kansas City',
  'St. Louis',
  'Nashville',
  'Memphis',
  'Birmingham',
  'Atlanta',
  'Jacksonville',
  'Miami',
  'Orlando',
  'Tampa',
  'Charlotte',
  'Raleigh',
  'Richmond',
  'Norfolk',
  'Baltimore',
  'Washington',
  'Philadelphia',
  'New York',
  'Boston',
  'Hartford',
  'Providence',
  'Buffalo',
  'Rochester',
  'Syracuse',
  'Albany',
  'Pittsburgh',
  'Cleveland',
  'Cincinnati',
  'Columbus',
  'Detroit',
  'Grand Rapids',
  'Milwaukee',
  'Chicago',
  'Indianapolis',
  'Minneapolis',
  'Des Moines',
  'Omaha',
  'Wichita',
  'Little Rock',
  'New Orleans',
  'Baton Rouge',
  'Jackson',
  'Mobile',
  'Montgomery',
  'Tallahassee',
  'Gainesville',
  'Fort Lauderdale',
  'West Palm Beach',
  'Fort Myers',
  'Sarasota',
  'Clearwater',
  'St. Petersburg',
  'Lakeland',
  'Daytona Beach',
  'Melbourne',
  'Vero Beach',
  'Pensacola',
  'Panama City',
  'Gulfport',
  'Biloxi',
  'Hattiesburg',
  'Meridian'
] as const;

export type CanonicalOffice = typeof CANONICAL_OFFICES[number];

export function isValidOffice(office: string): office is CanonicalOffice {
  return CANONICAL_OFFICES.includes(office as CanonicalOffice);
}

export function normalizeOfficeName(office: string): string {
  // Basic normalization - trim whitespace and handle common variations
  const normalized = office.trim();
  
  // Handle common variations
  const variations: Record<string, string> = {
    'PHX': 'Phoenix',
    'ATX': 'Austin',
    'DFW': 'Dallas',
    'HOU': 'Houston',
    'TUS': 'Tucson',
    'LAS': 'Las Vegas',
    'DEN': 'Denver',
    'SLC': 'Salt Lake City',
    'ABQ': 'Albuquerque',
    'SAT': 'San Antonio',
    'ELP': 'El Paso',
    'OKC': 'Oklahoma City',
    'KC': 'Kansas City',
    'STL': 'St. Louis',
    'BNA': 'Nashville',
    'MEM': 'Memphis',
    'BHM': 'Birmingham',
    'ATL': 'Atlanta',
    'JAX': 'Jacksonville',
    'MIA': 'Miami',
    'MCO': 'Orlando',
    'TPA': 'Tampa',
    'CLT': 'Charlotte',
    'RDU': 'Raleigh',
    'RIC': 'Richmond',
    'ORF': 'Norfolk',
    'BWI': 'Baltimore',
    'DCA': 'Washington',
    'PHL': 'Philadelphia',
    'NYC': 'New York',
    'BOS': 'Boston',
    'BDL': 'Hartford',
    'PVD': 'Providence',
    'BUF': 'Buffalo',
    'ROC': 'Rochester',
    'SYR': 'Syracuse',
    'ALB': 'Albany',
    'PIT': 'Pittsburgh',
    'CLE': 'Cleveland',
    'CVG': 'Cincinnati',
    'CMH': 'Columbus',
    'DTW': 'Detroit',
    'GRR': 'Grand Rapids',
    'MKE': 'Milwaukee',
    'ORD': 'Chicago',
    'IND': 'Indianapolis',
    'MSP': 'Minneapolis',
    'DSM': 'Des Moines',
    'OMA': 'Omaha',
    'ICT': 'Wichita',
    'LIT': 'Little Rock',
    'MSY': 'New Orleans',
    'BTR': 'Baton Rouge',
    'JAN': 'Jackson',
    'MOB': 'Mobile',
    'MGM': 'Montgomery',
    'TLH': 'Tallahassee',
    'GNV': 'Gainesville',
    'FLL': 'Fort Lauderdale',
    'PBI': 'West Palm Beach',
    'RSW': 'Fort Myers',
    'SRQ': 'Sarasota',
    'PIE': 'Clearwater',
    'LAL': 'Lakeland',
    'DAB': 'Daytona Beach',
    'MLB': 'Melbourne',
    'VRB': 'Vero Beach',
    'PNS': 'Pensacola',
    'PFN': 'Panama City',
    'GPT': 'Gulfport',
    'BIX': 'Biloxi',
    'HBG': 'Hattiesburg',
    'MEI': 'Meridian',
    'TUP': 'Tupelo',
    'GLH': 'Greenville',
    'STF': 'Starkville',
    'UOX': 'Oxford',
    'GTR': 'Columbus',
    'WPT': 'West Point',
    'CRX': 'Corinth',
    'GWO': 'Greenwood',
    'YAZ': 'Yazoo City',
    'HEZ': 'Natchez',
    'VKS': 'Vicksburg',
    'MCB': 'McComb',
    'BRK': 'Brookhaven',
    'PCY': 'Picayune',
    'BSL': 'Bay St. Louis',
    'PCH': 'Pass Christian',
    'LGB': 'Long Beach',
    'OSI': 'Ocean Springs',
    'PGL': 'Pascagoula',
    'MPT': 'Moss Point',
    'DIB': 'D\'Iberville',
    'SMT': 'St. Martin',
    'WLM': 'Woolmarket',
    'SAU': 'Saucier',
    'LYM': 'Lyman',
    'LAT': 'Latimer',
    'HUR': 'Hurley',
    'ESC': 'Escatawpa',
    'VAN': 'Vancleave',
    'WAD': 'Wade',
    'KRE': 'Kreole',
    'BIG': 'Big Point',
    'BEN': 'Benndale',
    'MCH': 'McHenry',
    'PKN': 'Perkinston',
    'WIG': 'Wiggins',
    'STW': 'Stonewall',
    'LUC': 'Lucedale',
    'LEA': 'Leakesville',
    'LEF': 'Leaf',
    'MCL': 'McLain',
    'BEA': 'Beaumont',
    'NAU': 'New Augusta',
    'SEM': 'Seminary',
    'SUM': 'Sumrall',
    'PUR': 'Purvis',
    'LUM': 'Lumberton',
    'POP': 'Poplarville',
    'CRO': 'Crosby',
    'CAR': 'Carriere',
    'NIC': 'Nicholson',
    'KIL': 'Kiln',
    'DIA': 'Diamondhead'
  };
  
  return variations[normalized.toUpperCase()] || normalized;
}
