#!/bin/bash
# Deploy and Sync Script
# This script helps trigger migrations and sync after deployment

echo "🚀 RepCard Deployment & Sync Helper"
echo "======================================"
echo ""
echo "✅ Code has been pushed to GitHub (commit 1ca3433)"
echo "⏳ Vercel is automatically deploying..."
echo ""
echo "📋 Next Steps:"
echo ""
echo "1. Wait for Vercel deployment to complete (~2-3 minutes)"
echo "   Check: https://vercel.com/dashboard"
echo ""
echo "2. Run Migration 028 in production:"
echo "   npx tsx scripts/run-repcard-migrations.ts"
echo "   (This will apply reschedule tracking schema)"
echo ""
echo "3. Trigger full sync to populate reschedule data:"
echo "   curl -X POST 'https://your-domain.com/api/admin/repcard/sync?type=full'"
echo ""
echo "4. Verify reschedule metrics:"
echo "   Open dashboard: https://your-domain.com"
echo "   Navigate to: RepCard Analytics section"
echo "   Check: Reschedule Metrics card should display data"
echo ""
echo "======================================"
echo ""
echo "🔗 Deployment Features:"
echo "  • Reschedule tracking (migration 028)"
echo "  • Reschedule metrics dashboard component"
echo "  • Appointment history API endpoint"
echo "  • Visual reschedule indicators (color-coded cards)"
echo "  • Top reschedulers leaderboard"
echo "  • Fixed leaderboard (384 users instead of 32)"
echo ""
