name: Deploy Preview

on:
  push:
    branches-ignore: [ "main" ]
  pull_request:
    branches: [ "**" ]

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run quality checks
        run: |
          npm run type-check
          npm run lint
          npm run test:unit -- --coverage

      - name: Install Vercel CLI
        run: npm i -g vercel@latest

      - name: Export Vercel env
        run: |
          echo "VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }}" >> $GITHUB_ENV
          echo "VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID }}" >> $GITHUB_ENV
          echo "VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID }}" >> $GITHUB_ENV

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel (Preview)
        id: deploy
        run: |
          URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})
          echo "preview_url=$URL" >> $GITHUB_OUTPUT

      - name: Comment Preview URL on PR
        if: github.event_name == 'pull_request'
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            ✅ Preview deployed: ${{ steps.deploy.outputs.preview_url }}

      - name: Run smoke tests against preview
        env:
          BASE_URL: ${{ steps.deploy.outputs.preview_url }}
        run: npm run test:smoke


